changelog:
  exclude:
    authors:
      - dependabot
    labels:
      - no-release

  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking change

    - title: Bug Fixes
      labels:
        - fix
        - bug fix

    - title: Features
      labels:
        - feature
        - feat

    - title: Other Changes
      labels:
        - change
