name: Lint, Test and Build

on:
  workflow_call:
  workflow_dispatch:

env:
  DEFAULT_NODE_VERSION: 20.x

jobs:
  job_lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout, Setup Node.js v${{ env.DEFAULT_NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}

      - name: Build
        run: npm run lint

  job_test_and_build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 20.x

    name: Test and Build ( ${{ matrix.os }}, Node.js v${{ matrix.node-version }} )

    runs-on: ${{ matrix.os }}
    needs: job_lint

    steps:
      - name: Checkout, Setup Node.js v${{ matrix.node-version }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: npm test
        env:
          COVERAGE: SKIP
