name: Create GitHub Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout, Setup Node.js v20.x and Install dependencies
        uses: manferlo81/action-checkout-node-install@initial
        with:
          node-version: 20.x

      - name: Build
        run: npm run build

      - name: Create Tarball
        run: npm pack

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          files: foreach-prop-*.tgz

      - name: Show release URL
        run: echo "GitHub Release Created! ( ${{ steps.create-release.outputs.url }} )" >> $GITHUB_STEP_SUMMARY
